title: My GitHub Pages Practice
author: JGL
# email: your-email@domain.com
description: A blog example to complete the GitHub Pages free course. That's all.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jg-lopez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
